### PR TITLE
add sdk base

### PR DESCRIPTION
**Pull request by 21e8**
- added base for sdk/npm build 
- transferred test functions as far as I could
- have not yet replaced any of the test values, wanna understand limitations and architecture better before I do

also no clue why yarn removed all the quotes in the lockfile

### CODE REVIEW

**Comment by 21e8** [comment]
Also: host signatures are not being done within the function anymore, gives more flexibility and lets us use e.g. Phantom later (which doesn't expose private keys)

**Comment by nilz3ro** [comment]
Hey @21e8 thank you for this! Can you please make a new directory in the project root called `sdk` and also could you please [add a GPG key to your Github profile](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account)?

**Comment by 21e8** [comment]
hi @nilz3ro, I created a separate package.json with only what is needed! I hope this is what you had in mind

**Comment by nilz3ro** [comment]
@21e8 Looks good, lmk when it's no longer WIP.

**Comment by 21e8** [comment]
@nilz3ro I removed everything that wasnt yet fully clear to me. Also made sure the methods can return both, transactions and instructions.

I have yet to add the "firing the request" functionality and the methods here might not allow for full functionality, but mebbe we can merge to keep it all overseeable

**Pull request merged**
